---
title: Rocky Knows
baseline: Things I know
description: usually things I know I should share and hope it helps you
keywords: Intune, Education
author: Rocky Pabillore
baseurl: "/"
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
output:
  formats:
  - name: netlify_redirects
    mediatype: text/plain
    extension: ''
virtualpages:
- path: admin
  title: Content Manager (Netlify CMS)
  layout: admin/index
  output: html
- path: _redirects
  output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
optimize:
  enabled: true
